import { test, expect } from '@playwright/test'

test('version 2 upgrade preserves evidence and enables state editing',async({page})=>{
  await page.goto('/')
  await page.getByText('Rules & guides',{exact:true}).click()
  await page.getByRole('button',{name:'Upgrade draft to version 2'}).click()
  await expect(page.getByText('Pack format 2 · State engine 1')).toBeVisible()
  await page.getByRole('button',{name:'State definitions and preview'}).click()
  await page.getByLabel('State variable definitions (JSON)').fill('[{"id":"locks","label":"Lock credits","type":"counter","scope":"game","initial":0}]')
  await page.getByRole('button',{name:'Apply definitions'}).click()
  await page.reload()
  await page.getByText('Rules & guides',{exact:true}).click()
  await expect(page.getByText('Pack format 2 · State engine 1')).toBeVisible()
  await page.getByRole('button',{name:'State definitions and preview'}).click()
  await expect(page.getByLabel('State variable definitions (JSON)')).toHaveValue(/locks/)
})
test('review decisions survive refresh; sandbox publication stays separate',async({page})=>{
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'A good game starts with a clear plan.'})).toBeVisible()
  await page.screenshot({path:'artifacts/admin-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Review research',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Evidence before advice.'})).toBeVisible()
  const row=page.locator('article').filter({has:page.getByRole('heading',{name:'Trooper starts with the drop targets'})})
  await row.getByLabel('Review note').fill('Verified source for sandbox test')
  await row.getByRole('button',{name:'Approve',exact:true}).click()
  await expect(page.getByText('Approved: Trooper starts with the drop targets (sandbox only)')).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'Review research',exact:true}).click()
  await page.getByRole('button',{name:'Approved',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Trooper starts with the drop targets'})).toBeVisible()
  await page.getByText('Publish packs',{exact:true}).click()
  await page.getByRole('button',{name:'Create sandbox snapshot'}).click()
  await expect(page.getByText(/Sandbox snapshot created/)).toBeVisible()
  await expect(page.getByText('Workshop table — version 1')).toBeVisible()
})
test('shot edits persist and mobile layout fits',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Open playfield editor'}).click()
  await page.getByLabel('Shot name',{exact:true}).fill('Test left ramp')
  await page.getByRole('button',{name:'Save draft'}).click()
  await page.reload()
  await page.getByRole('button',{name:'Open playfield editor'}).click()
  await expect(page.getByLabel('Shot name',{exact:true})).toHaveValue('Test left ramp')
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('heading',{name:'Every shot has a place.'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})
test('budget validation rejects an invalid cap',async({page})=>{
  await page.goto('/')
  await page.getByText('Settings',{exact:true}).click()
  await page.getByLabel('Monthly limit (AUD)').fill('75')
  await page.getByRole('button',{name:'Save spending cap'}).click()
  await expect(page.getByText('A$75',{exact:true})).toBeVisible()
  await page.getByLabel('Monthly limit (AUD)').fill('0')
  await page.getByRole('button',{name:'Save spending cap'}).click()
  await expect(page.getByText('Enter a monthly limit from A$1 to A$10,000.')).toBeVisible()
  await page.screenshot({path:'artifacts/admin-settings.png',fullPage:true})
})

test('phone opens with usable navigation and editor',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByRole('button',{name:'Open playfield editor'}).click()
  await expect(page.getByLabel('Shot name',{exact:true})).toHaveValue('Left ramp')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:'artifacts/admin-mobile.png',fullPage:true,animations:'disabled'})
})
