import { mkdirSync, writeFileSync, copyFileSync } from 'node:fs'
const out = (path, data) => { mkdirSync(path.substring(0, path.lastIndexOf('/')), { recursive: true }); writeFileSync(path, typeof data === 'string' ? data : JSON.stringify(data, null, 2) + '\n') }
const variantId = 'workshop-demo'
const source = { id: 'original-demo', title: 'Original fictional demonstration', url: 'https://example.invalid/pinballpilot/demo', kind: 'original', locator: 'content/demo-pack.json', accessedAt: '2026-10-09', notes: 'Original software test fixture. These rules do not describe a real pinball machine. Diagram created for this project, CC0.' }
const names = [['left-ramp','Left ramp','ramp',.28,.34],['right-ramp','Right ramp','ramp',.73,.35],['left-orbit','Left orbit','orbit',.15,.24],['right-orbit','Right orbit','orbit',.85,.24],['drop-bank','Drop targets','target',.42,.46],['lock','Ball lock','lock',.58,.26],['scoop','Mode scoop','scoop',.25,.55],['bullseye','Bullseye','target',.5,.16],['spinner','Spinner lane','lane',.77,.51],['bumpers','Bumpers','bumper',.39,.25],['left-inlane','Left inlane','lane',.2,.74],['right-inlane','Right inlane','lane',.8,.74]]
const shots = names.map(([id,name,type,x,y],i) => ({id,name,type,geometry:{point:{x,y},...(id==='drop-bank'?{polygon:[{x:.34,y:.43},{x:.50,y:.43},{x:.50,y:.49},{x:.34,y:.49}]}:{})},description:`${name} on the fictional Workshop table. Tap a guide to see its role.`,difficulty: i===4?.35:.2+(i%4)*.15,risk:.15+(i%3)*.13}))
const entries = [
 ['ramp-build','left-ramp','Build the ramp bonus','Shoot the left ramp.','This qualifies the ramp bonus and gives you a repeatable scoring route.',[], 'ramp-ready',.5,.5],
 ['ramp-collect','right-ramp','Collect the ramp bonus','Shoot the right ramp.','The left ramp has qualified this bonus; the right ramp collects it.',['ramp-ready'],'ramp-bonus',.9,.6],
 ['mode-qualify','spinner','Qualify a mode','Shoot the spinner lane.','This lights the mode scoop for an advanced scoring sequence.',[],'mode-ready',.6,.4],
 ['mode-start','scoop','Start a mode','Shoot the mode scoop.','Starting the mode makes the bullseye award available.',['mode-ready'],'mode-active',.6,.6],
 ['mode-finish','bullseye','Finish the mode','Shoot the bullseye.','With the mode active, this shot collects its scoring award.',['mode-active'],'mode-complete',1,.7],
 ['light-lock','drop-bank','Light the lock','Complete the drop-target bank.','This lights the ball lock, the first step toward multiball.',[],'lock-lit',.2,1],
 ['lock-one','lock','Lock the first ball','Shoot the lit ball lock.','This records your first lock toward multiball.',['lock-lit'],'one-locked',.3,1],
 ['lock-two','lock','Lock the second ball','Shoot the ball lock again.','The second lock brings you one step closer.',['one-locked'],'two-locked',.3,1],
 ['lock-three','lock','Start multiball','Shoot the ball lock for the third time.','The third lock starts this demonstration machine’s multiball.',['two-locked'],'multiball-active',.7,1],
 ['jackpot','left-orbit','Collect a jackpot','Shoot the left orbit.','During multiball, the left orbit collects a jackpot.',['multiball-active'],'jackpot-collected',1,.8],
]
const claims = entries.map(([id,,title,instruction,why]) => ({id:`claim-${id}`,variantId,kind:'recommendation',title,body:`${instruction} ${why}`,sourceIds:[source.id],status:'approved',revision:1,reviewedRevision:1,reviewNote:'Original fictional fixture; not authentic machine content.',software:'demo-1'}))
claims.push({id:'claim-guide',variantId,kind:'recommendation',title:'Demonstration guide sequences',body:'Fictional demo: use ramp bonus for simple scoring, the spinner/scoop/bullseye sequence for advanced scoring, or drop targets and three locks for multiball.',sourceIds:[source.id],status:'approved',revision:1,reviewedRevision:1,reviewNote:'Original fictional fixture.',software:'demo-1'})
const rules = entries.map(([id,shotId,,instruction,why,prerequisites,outcome,value,progression]) => ({id,shotId,claimIds:[`claim-${id}`],instruction,why,prerequisites,outcome,value,progression}))
const pack = {schemaVersion:1,variantId,version:1,name:'Workshop table',edition:'Fictional demonstration',manufacturer:'Pinball Pilot',demo:true,image:{path:'workshop.svg',license:'CC0-1.0 — original schematic created for Pinball Pilot',rightsConfirmed:true,width:600,height:1100},shots,rules,strategies:[{id:'simple-scoring',title:'Build a repeatable score',objective:'scoring',level:'simple',claimIds:['claim-guide'],steps:['ramp-build','ramp-collect']},{id:'advanced-scoring',title:'Start and finish a mode',objective:'scoring',level:'advanced',claimIds:['claim-guide'],steps:['mode-qualify','mode-start','mode-finish']},{id:'multiball',title:'Your route to multiball',objective:'multiball',level:'simple',claimIds:['claim-guide'],steps:['light-lock','lock-one','lock-two','lock-three','jackpot']}],claims,sources:[source]}
out('content/demo-pack.json',pack)
out('admin/app/data/demo-pack.json',pack)
out('android/app/src/main/assets/demo-pack.json',pack)
const diagram = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="1100" viewBox="0 0 600 1100"><rect width="600" height="1100" rx="70" fill="#17243a"/><rect x="28" y="22" width="544" height="1056" rx="80" fill="none" stroke="#8aacc1" stroke-width="6"/><path d="M85 870 V220 Q85 55 300 55 Q520 55 520 220 V870" fill="none" stroke="#476787" stroke-width="20"/><path d="M110 880 V300 Q170 215 210 335 L165 600 M485 880 V320 Q405 230 415 385 L465 610" fill="none" stroke="#739aaf" stroke-width="26"/><path d="M110 880 V300 Q170 215 210 335 L165 600 M485 880 V320 Q405 230 415 385 L465 610" fill="none" stroke="#c6d8dc" stroke-width="3"/><path d="M160 810 L205 905 L135 890 Z M440 810 L395 905 L465 890 Z" fill="#c48346" stroke="#ffcf85" stroke-width="4"/><path d="M190 960 L268 995 M410 960 L332 995" fill="none" stroke="#f3eee5" stroke-width="24" stroke-linecap="round"/><g fill="#344f6a" stroke="#93c7db" stroke-width="4"><circle cx="215" cy="275" r="30"/><circle cx="285" cy="250" r="30"/><circle cx="265" cy="325" r="30"/></g><g fill="#e0a84d"><rect x="200" y="475" width="25" height="60" rx="5"/><rect x="235" y="475" width="25" height="60" rx="5"/><rect x="270" y="475" width="25" height="60" rx="5"/></g><ellipse cx="145" cy="610" rx="37" ry="25" fill="#101826" stroke="#93c7db" stroke-width="5"/><circle cx="300" cy="170" r="30" fill="#e0a84d"/><circle cx="300" cy="170" r="12" fill="#202c41"/><path d="M310 800 L290 700 L310 600" fill="none" stroke="#d6a85e" stroke-width="5"/><g font-family="sans-serif" text-anchor="middle"><text x="300" y="680" fill="#f4f0e8" font-size="32" font-weight="bold">WORKSHOP</text><text x="300" y="715" fill="#93c7db" font-size="18">Fictional demonstration</text><text x="300" y="1040" fill="#93c7db" font-size="16">PINBALL PILOT</text></g></svg>`
out('content/workshop.svg',diagram)
out('admin/public/workshop.svg',diagram)
out('android/app/src/main/assets/workshop.svg',diagram)
const sources = [
 {id:'stern-card',title:'Stern Iron Maiden instruction card',url:'https://pinball-universe.de/mediafiles/pdf/stern-pinball/instruction-cards/imd-instruction-card-en.pdf',kind:'manufacturer',locator:'Instruction card, game objectives',accessedAt:'2026-10-09',notes:'Manufacturer-authored card hosted by a distributor. Short summaries only; no redistribution of artwork. Check against installed software.'},
 {id:'stern-pro',title:'Stern Iron Maiden Pro model page',url:'https://www.sternpinball.com/game/iron-maiden/pro/',kind:'manufacturer',locator:'Explore the playfield',accessedAt:'2026-10-09',notes:'Pro-specific physical features. No image reuse permission established.'},
 {id:'stern-manual',title:'Stern Iron Maiden Pro service manual',url:'https://wp.sternpinball.com/wp-content/uploads/2019/03/IronMaiden_Pro_web.pdf',kind:'manufacturer',locator:'Sections 3 and 5: switch reference and playfield assemblies',accessedAt:'2026-10-09',notes:'Hardware and naming reference; not a complete gameplay rulesheet.'},
 {id:'tilt-rules',title:'Iron Maiden community rulesheet',url:'https://tiltforums.com/t/iron-maiden-pinball-rulesheet/3787',kind:'rulesheet',locator:'Trooper / Mummy multiball sections',accessedAt:'2026-10-09',notes:'Community evidence. Verify edition, software, and operator settings. Pending detailed review.'},
]
const research = [
 ['trooper-qualify','Trooper starts with the drop targets','Completing drop targets enables Trooper locks. Confirm the lit lock indicators before attempting the lock shots.','stern-card','fact'],
 ['trooper-three','Three Trooper locks start multiball','Collect three qualified locks to begin Trooper Multiball.','stern-card','fact'],
 ['mummy','Mummy uses the captive ball','The sarcophagus captive ball advances Mummy Multiball. Exact hit counts and the Pro lock sequence still need verification.','stern-card','fact'],
 ['eddie','Eddie letters lead to modes','Collect EDDIE letters through the main shots, then use the middle shot to begin a mode. Check the lit indicators and display.','stern-card','fact'],
 ['four-flippers','Pro has four flippers','The Pro playfield has four flippers, including a full-size upper-right flipper.','stern-pro','fact'],
 ['jump-ramp','Pro centre jump ramp','The Pro has a stainless-steel centre jump ramp and a segmented bullseye target.','stern-pro','fact'],
 ['start-trooper','Simple multiball starting plan','For a first learning goal, follow drop targets into the lit Trooper locks. This recommendation is an editorial inference from the instruction card and needs playtesting.','stern-card','recommendation'],
]
const maiden = {variantId:'iron-maiden-pro',name:'Iron Maiden: Legacy of the Beast',edition:'Pro',manufacturer:'Stern',demo:false,sources,claims:research.map(([id,title,body,sourceId,kind]) => ({id,variantId:'iron-maiden-pro',kind,title,body,sourceIds:[sourceId],status:'pending',revision:1,reviewedRevision:null,reviewNote:'',software:'Unverified — capture the installed version during the next visit'}))}
out('content/iron-maiden-research.json',maiden)
out('admin/app/data/iron-maiden-research.json',maiden)
const maidenDraft={schemaVersion:1,variantId:maiden.variantId,version:1,name:maiden.name,edition:maiden.edition,manufacturer:maiden.manufacturer,demo:false,image:{path:'/awaiting-image.svg',license:'Rights not yet recorded',rightsConfirmed:false,width:600,height:1100},shots:[],rules:[],strategies:[],claims:maiden.claims,sources:maiden.sources}
out('content/iron-maiden-draft.json',maidenDraft)
out('admin/app/data/iron-maiden-draft.json',maidenDraft)
out('admin/public/awaiting-image.svg','<svg xmlns="http://www.w3.org/2000/svg" width="600" height="1100"><rect width="600" height="1100" fill="#202c41"/><g fill="#b8c6d7" font-family="sans-serif" text-anchor="middle"><text x="300" y="520" font-size="26">Upload a reference playfield</text><text x="300" y="560" font-size="18">Then position and verify each shot</text></g></svg>')
console.log('Generated fictional pack, original schematic and pending Iron Maiden evidence.')
